version: '3'
services:
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
  samples-mongo:
    build: .
    ports:
    - "9090:9090"
    depends_on:
      - mongo-db
    links:
      - mongo-db
